package store

import (
	"context"
	"errors"
	"time"

	"github.com/JuribaDev/yalla/internal/controlplane/apierr"
	"github.com/jackc/pgx/v5"
)

// APIKey is the source-of-truth representation of a row in the api_keys table.
// It is the persistence-layer shape; the HTTP request and response shapes are
// the job of the httpapi layer. No field holds a usable credential: SecretHash
// is a one-way hash and Prefix is the public lookup key. The plaintext token
// is generated by internal/controlplane/auth, shown to its owner once, and
// never reaches this struct or the database.
type APIKey struct {
	ID             string
	OrganizationID string
	Prefix         string
	SecretHash     string
	Name           string
	Scopes         []string
	// CreatedBy is the id of the user who minted the key, or "" when the key
	// has no attributed creator (the api_keys.created_by column is nullable).
	CreatedBy string
	// ServiceAccountID is the id of the service account that owns the key, or
	// "" when the key is not owned by a service account (the
	// api_keys.service_account_id column is nullable). A non-human principal —
	// CI or automation — authenticates with a service-account-owned key. The
	// composite foreign key (organization_id, service_account_id) guarantees
	// the owning service account is in the same organization as the key.
	ServiceAccountID string
	ExpiresAt        *time.Time
	RevokedAt        *time.Time
	LastUsedAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// IsRevoked reports whether the key has been explicitly revoked.
func (k APIKey) IsRevoked() bool { return k.RevokedAt != nil }

// IsExpired reports whether the key has a time bound that now is at or past.
func (k APIKey) IsExpired(now time.Time) bool {
	return k.ExpiresAt != nil && !now.Before(*k.ExpiresAt)
}

// IsUsable reports whether the key may be used to authenticate at now: it must
// be neither revoked nor expired. Finding a key by its prefix and verifying
// its secret is necessary but not sufficient — the caller must also check
// IsUsable before trusting the key.
func (k APIKey) IsUsable(now time.Time) bool {
	return !k.IsRevoked() && !k.IsExpired(now)
}

// APIKeyRepository is the persistence layer for API keys. It follows the
// repository transaction pattern: mutations require a *Tx (so they can only
// run inside Store.Write, never separated from their authorization and quota
// checks), reads accept a Querier, and every statement is fully parameterized.
//
// Tenant scoping: Get, ListByOrganization, TouchLastUsed, and Revoke all scope
// by organization_id before key id, so a key id from another organization can
// never match. FindByPrefix is the one deliberate exception — it is the
// authentication lookup, which runs before the caller's tenant is known.
type APIKeyRepository struct{}

// NewAPIKeyRepository returns an APIKeyRepository.
func NewAPIKeyRepository() *APIKeyRepository { return &APIKeyRepository{} }

// apiKeyColumns is the column list returned by every api_keys query, in the
// order scanAPIKey expects.
const apiKeyColumns = `id, organization_id, prefix, secret_hash, name, scopes, ` +
	`created_by, service_account_id, expires_at, revoked_at, last_used_at, created_at, updated_at`

// scanAPIKey scans one api_keys row, in apiKeyColumns order, into an APIKey.
func scanAPIKey(row pgx.Row) (APIKey, error) {
	var (
		k                APIKey
		createdBy        *string
		serviceAccountID *string
	)
	if err := row.Scan(
		&k.ID, &k.OrganizationID, &k.Prefix, &k.SecretHash, &k.Name, &k.Scopes,
		&createdBy, &serviceAccountID, &k.ExpiresAt, &k.RevokedAt, &k.LastUsedAt, &k.CreatedAt, &k.UpdatedAt,
	); err != nil {
		return APIKey{}, err
	}
	if createdBy != nil {
		k.CreatedBy = *createdBy
	}
	if serviceAccountID != nil {
		k.ServiceAccountID = *serviceAccountID
	}
	return k, nil
}

// Insert writes a new API key row inside tx and returns the persisted row,
// including the database-assigned timestamps. It requires a *Tx — not a bare
// Querier — so a key can never be created outside the transaction that also
// carries its authorization and quota checks. A duplicate id or prefix is
// reported as a Conflict. The caller is responsible for hashing the secret via
// internal/controlplane/auth before building the APIKey: this layer only ever
// receives Prefix and SecretHash, never a plaintext credential.
func (r *APIKeyRepository) Insert(ctx context.Context, tx *Tx, k APIKey) (APIKey, error) {
	if tx == nil {
		return APIKey{}, apierr.Internal(errors.New("store: APIKeyRepository.Insert called with a nil transaction"))
	}
	var createdBy *string
	if k.CreatedBy != "" {
		createdBy = &k.CreatedBy
	}
	var serviceAccountID *string
	if k.ServiceAccountID != "" {
		serviceAccountID = &k.ServiceAccountID
	}
	scopes := k.Scopes
	if scopes == nil {
		// A nil slice would be stored as NULL; the column is NOT NULL DEFAULT
		// '{}', so normalise to an empty array.
		scopes = []string{}
	}
	row := tx.QueryRow(ctx,
		`INSERT INTO api_keys
		   (id, organization_id, prefix, secret_hash, name, scopes,
		    created_by, service_account_id, expires_at, revoked_at, last_used_at)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
		 RETURNING `+apiKeyColumns,
		k.ID, k.OrganizationID, k.Prefix, k.SecretHash, k.Name, scopes,
		createdBy, serviceAccountID, k.ExpiresAt, k.RevokedAt, k.LastUsedAt)
	created, err := scanAPIKey(row)
	if err != nil {
		return APIKey{}, mapWriteError(err, "an api key with this id or prefix already exists")
	}
	return created, nil
}

// FindByPrefix returns the API key whose public prefix is prefix. This is the
// authentication lookup, and it is the ONE repository read that is deliberately
// NOT tenant-scoped: authentication happens before the caller's tenant is
// known, and the prefix itself is the lookup key. The prefix is globally unique
// (a UNIQUE constraint) and unguessable, and the row it returns carries its own
// OrganizationID, so every caller scopes subsequent work by key.OrganizationID.
//
// Finding the row is not authentication: the caller must still verify the
// secret with a constant-time hash comparison (auth.VerifySecret) and check
// APIKey.IsUsable. A missing prefix is reported as a typed apierr.NotFound; the
// auth layer maps that to an Unauthenticated response.
func (r *APIKeyRepository) FindByPrefix(ctx context.Context, q Querier, prefix string) (APIKey, error) {
	row := q.QueryRow(ctx,
		`SELECT `+apiKeyColumns+` FROM api_keys WHERE prefix = $1`, prefix)
	k, err := scanAPIKey(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return APIKey{}, apierr.NotFound("api_key", prefix)
	}
	if err != nil {
		return APIKey{}, apierr.StoreUnavailable(err)
	}
	return k, nil
}

// Get returns the API key identified by keyID within organizationID. The query
// is tenant scoped: it filters by organization_id first, so a key id that
// belongs to another organization simply does not match and is reported as
// NotFound — a cross-tenant id can never reveal another organization's data.
func (r *APIKeyRepository) Get(ctx context.Context, q Querier, organizationID, keyID string) (APIKey, error) {
	row := q.QueryRow(ctx,
		`SELECT `+apiKeyColumns+` FROM api_keys WHERE organization_id = $1 AND id = $2`,
		organizationID, keyID)
	k, err := scanAPIKey(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return APIKey{}, apierr.NotFound("api_key", keyID)
	}
	if err != nil {
		return APIKey{}, apierr.StoreUnavailable(err)
	}
	return k, nil
}

// ListByOrganization returns every API key owned by organizationID, oldest
// first. The query is tenant scoped, so it can never return another
// organization's keys.
func (r *APIKeyRepository) ListByOrganization(ctx context.Context, q Querier, organizationID string) ([]APIKey, error) {
	rows, err := q.Query(ctx,
		`SELECT `+apiKeyColumns+`
		 FROM api_keys
		 WHERE organization_id = $1
		 ORDER BY created_at, id`,
		organizationID)
	if err != nil {
		return nil, apierr.StoreUnavailable(err)
	}
	defer rows.Close()

	var keys []APIKey
	for rows.Next() {
		k, err := scanAPIKey(rows)
		if err != nil {
			return nil, apierr.StoreUnavailable(err)
		}
		keys = append(keys, k)
	}
	if err := rows.Err(); err != nil {
		return nil, apierr.StoreUnavailable(err)
	}
	return keys, nil
}

// ListByServiceAccount returns every API key owned by the service account
// identified by (organizationID, serviceAccountID), oldest first. The query is
// tenant scoped by organization_id, so it can never return another
// organization's keys — and a service account id from another organization
// simply matches no rows.
func (r *APIKeyRepository) ListByServiceAccount(ctx context.Context, q Querier, organizationID, serviceAccountID string) ([]APIKey, error) {
	rows, err := q.Query(ctx,
		`SELECT `+apiKeyColumns+`
		 FROM api_keys
		 WHERE organization_id = $1 AND service_account_id = $2
		 ORDER BY created_at, id`,
		organizationID, serviceAccountID)
	if err != nil {
		return nil, apierr.StoreUnavailable(err)
	}
	defer rows.Close()

	var keys []APIKey
	for rows.Next() {
		k, err := scanAPIKey(rows)
		if err != nil {
			return nil, apierr.StoreUnavailable(err)
		}
		keys = append(keys, k)
	}
	if err := rows.Err(); err != nil {
		return nil, apierr.StoreUnavailable(err)
	}
	return keys, nil
}

// TouchLastUsed records that the key identified by (organizationID, keyID) was
// used at usedAt. It requires a *Tx and is tenant scoped. A key id that belongs
// to another organization does not match and is reported as NotFound — a
// cross-tenant id can never update another organization's row.
func (r *APIKeyRepository) TouchLastUsed(ctx context.Context, tx *Tx, organizationID, keyID string, usedAt time.Time) error {
	if tx == nil {
		return apierr.Internal(errors.New("store: APIKeyRepository.TouchLastUsed called with a nil transaction"))
	}
	tag, err := tx.Exec(ctx,
		`UPDATE api_keys SET last_used_at = $3 WHERE organization_id = $1 AND id = $2`,
		organizationID, keyID, usedAt)
	if err != nil {
		return mapWriteError(err, "the api key could not be updated")
	}
	if tag.RowsAffected() == 0 {
		return apierr.NotFound("api_key", keyID)
	}
	return nil
}

// Revoke marks the key identified by (organizationID, keyID) as revoked at
// revokedAt. It requires a *Tx and is tenant scoped. Revocation is idempotent:
// COALESCE keeps the first revocation timestamp, so revoking an already-revoked
// key is a no-op success rather than an error. A key id that belongs to another
// organization does not match and is reported as NotFound.
func (r *APIKeyRepository) Revoke(ctx context.Context, tx *Tx, organizationID, keyID string, revokedAt time.Time) error {
	if tx == nil {
		return apierr.Internal(errors.New("store: APIKeyRepository.Revoke called with a nil transaction"))
	}
	tag, err := tx.Exec(ctx,
		`UPDATE api_keys
		 SET revoked_at = COALESCE(revoked_at, $3)
		 WHERE organization_id = $1 AND id = $2`,
		organizationID, keyID, revokedAt)
	if err != nil {
		return mapWriteError(err, "the api key could not be revoked")
	}
	if tag.RowsAffected() == 0 {
		return apierr.NotFound("api_key", keyID)
	}
	return nil
}

// APIKeyReader is the store-backed read adapter the httpapi layer depends on
// for the GET /v1/organizations/{org_id}/api-keys endpoint surface. It mirrors
// MembershipReader and OrganizationReader — it composes the APIKeyRepository
// rather than issuing its own SQL, so the tenant-scoping guarantees the
// repository proves in its integration tests are inherited for free, and every
// method opens its own short-lived read transaction through Store.Read.
type APIKeyReader struct {
	store   *Store
	apiKeys *APIKeyRepository
}

// NewAPIKeyReader builds an APIKeyReader over store. It returns an error for a
// nil store so a misconfigured adapter fails at construction rather than on
// its first request.
func NewAPIKeyReader(s *Store) (*APIKeyReader, error) {
	if s == nil {
		return nil, errors.New("store: nil store")
	}
	return &APIKeyReader{store: s, apiKeys: NewAPIKeyRepository()}, nil
}

// ListAPIKeys returns every API key owned by organizationID, oldest first,
// reading them inside a short-lived read-only transaction. The read is tenant
// scoped: a cross-tenant id simply matches no rows and yields an empty list,
// never another organization's keys. A datastore failure is propagated as its
// own typed error.
func (r *APIKeyReader) ListAPIKeys(ctx context.Context, organizationID string) ([]APIKey, error) {
	var keys []APIKey
	err := r.store.Read(ctx, func(ctx context.Context, q Querier) error {
		var listErr error
		keys, listErr = r.apiKeys.ListByOrganization(ctx, q, organizationID)
		return listErr
	})
	if err != nil {
		return nil, err
	}
	return keys, nil
}
