apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - yalla-control-plane.yaml
images:
  - name: ghcr.io/juribadev/yalla-api
    newTag: 0.0.0-dev
  - name: ghcr.io/juribadev/yalla-worker
    newTag: 0.0.0-dev
